### ISSUE TITLE
doesnt work f me

### ISSUE THREAD

**Issue by spira007** [MateriApps/OpenCord#71] opened 2022-08-26 20:37 UTC
this is cursed...
![Screenshot_20220826-233725](https://user-images.githubusercontent.com/73871136/186987054-ee3c4367-2efe-4c85-8d79-e65ec9008947.png)
![Screenshot_20220826-233711](https://user-images.githubusercontent.com/73871136/186987055-378d8688-8cd0-464b-b2ad-79987a02aa12.png)

**Comment by spira007** [comment] 2022-08-26 20:39
also, 11 android, realmeui r edition (r for retard xuz it is just retarded version of realmeui) doesnt work on both of versions, last, and second last

**Comment by X1nto** [comment] 2022-08-26 20:41
A logcat would be helpful

**Comment by DiamondMiner88** [comment] 2022-08-26 22:26
What phone are you on?

**Comment by spira007** [comment] 2022-08-27 15:29
> A logcat would be helpful

where do i find it..



> What phone are you on?

Realme c21-y

**Comment by DiamondMiner88** [comment] 2022-08-27 17:40
**How do I provide a logcat?**

You will need:
- A computer
- ADB installed (<https://streamable.com/h0618w>)

1. Enable USB debugging in your phone's developer options
2. Run the following command in a terminal (cmd for Windows):
```sh
adb logcat -c
```
3. If you have not previously authorized adb on your phone, open it now and authorize your pc
4. Now open OpenCord and reproduce the issue
5. Run the following command now
```sh
adb logcat -d > logcat.txt
```
6. The generated logcat will be in your user home directory

**Comment by spira007** [comment] 2022-08-27 18:10
holy shit im just eater, not cooka so im just default guy that do nothing and cant anything :tf:

**Comment by daBroma** [comment] 2022-08-27 18:22
I had an aneurysm reading that message

**Comment by X1nto** [comment] 2022-08-27 21:39
> holy shit im just eater, not cooka so im just default guy that do nothing and cant anything :tf:

Well in that case I'm closing the issue since you can't do anything to help us.

**Closed by X1nto** 2022-08-27 21:39 UTC
